# Generated by Django 4.2.3 on 2023-07-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
